---
- name: "Generating compose file for {{ source_dir }}"
  ansible.builtin.shell: /bin/true
  changed_when: false
- name: Convert relative stack template dir path to absolute path
  ansible.builtin.set_fact:
    source_dir_abs: "{{ source_dir if source_dir is abs else playbook_dir + '/../stacks/' + source_dir }}" 
- name: Make sure destination directory exists
  ansible.builtin.file:
    path: "{{ dest_dir }}/{{ source_dir_abs | basename }}"
    state: directory
- name: Include vriables and secrets from .yaml files in stack template dir
  ansible.builtin.include_vars:
    dir: "{{ source_dir_abs }}"
    extensions:
    - 'yaml'
    ignore_unknown_extensions: true
- name: Putting generated compose.yaml in "{{ dest_dir }}/{{ source_dir_abs | basename }}/"
  ansible.builtin.template:
    src: "{{ source_dir_abs}}/compose.yaml.j2"
    dest: "{{ dest_dir }}/{{ source_dir_abs | basename }}/compose.yml"
