version: "3.8"

services:
  cleanup:
    container_name: docker-host-cleanup
    image: servivum/docker-host-cleanup:24.0
    environment:
      CRON_INTERVAL: $CRON_INTERVAL
      # PRUNE_BUILD_CACHES: 'true'
      PRUNE_BUILD_CACHES_FILTER: 'until=5m'
      # PRUNE_CONTAINERS: 'true'
      PRUNE_CONTAINERS_FILTER: 'until=5m'
      # PRUNE_IMAGES: 'true'
      PRUNE_IMAGES_FILTER: 'until=5m'
      # PRUNE_NETWORKS: 'true'
      PRUNE_NETWORKS_FILTER: 'until=5m'
      # PRUNE_VOLUMES: 'true'
    deploy:
      mode: global
    stop_grace_period: 1s
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
