---
- name: Generate compose.yaml for docker stack
  hosts: containerhost
  gather_facts: false
  become: false
  vars:
    stack_deployments_dir: "/home/harpreet/stacks"
    vault_pass_file: "/home/harpreet/secrets/vault_pass"

  tasks:
  - name: Convert relative stack template dir path to absolute path
    ansible.builtin.set_fact:
      stack_template_dir_abs: "{{ stack_template_dir if stack_template_dir is abs else playbook_dir + '/../../stacks/' + stack_template_dir }}" 
  - name: Make sure destination directory exists
    ansible.builtin.file:
      path: "{{ stack_deployments_dir }}/{{ stack_template_dir_abs | basename }}"
      state: directory
  - name: Include all .yaml files in stack template dir
    ansible.builtin.include_vars:
      dir: "{{ stack_template_dir_abs }}"
      extensions:
      - 'yaml'
      ignore_unknown_extensions: true
  - name: Generate compose.yaml based on variables
    ansible.builtin.template:
      src: "{{ stack_template_dir_abs}}/compose.yaml.j2"
      dest: "{{ stack_deployments_dir }}/{{ stack_template_dir_abs | basename }}/compose.yml"
