---
- name: Generate compose.yaml for docker stack
  hosts: containerhost
  gather_facts: false
  become: false
  vars:
    stack_deployments_dir: "/home/harpreet/stacks"
    vault_pass_file: "/home/harpreet/secrets/vault_pass"

  tasks:
  - name: Make sure destination directory exists
    ansible.builtin.file:
      path: "{{ stack_deployments_dir }}/{{ stack_template_dir | basename }}"
      state: directory
  - name: Include all .yaml files in stack template dir
    ansible.builtin.include_vars:
      dir: "{{ stack_template_dir }}"
      extensions:
      - 'yaml'
      ignore_unknown_extensions: true
  - name: Generate compose.yaml based on variables
    ansible.builtin.template:
      src: "{{ stack_template_dir}}/compose.yaml.j2"
      dest: "{{ stack_deployments_dir }}/{{ stack_template_dir | basename }}/compose.yml"
