#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SCRIPT_CALLED=$( basename -- "${BASH_SOURCE[0]}" )

if [ "$SCRIPT_CALLED" = "stack" ]; then
	if [ "$#" -lt 1 ]; then
		echo "ERROR: Specify an operations for the stack (e.g. start, stop etc)"
		exit 1
	fi
	SCRIPT_CALLED="$1"
	shift
fi

PROJECT_DIR=${1:-$PWD}
cd "$PROJECT_DIR"

ENV_FILE_OPTS=""
shopt -s nullglob
for env_file in *.env; do
	ENV_FILE_OPTS="${ENV_FILE_OPTS} --env-file $env_file"
done

case "$SCRIPT_CALLED" in
	start)
		docker compose $ENV_FILE_OPTS up -d
		;;
	stop)
		docker compose $ENV_FILE_OPTS down
		;;
	*)
		echo "ERROR: Undefined operattion $SCRIPT_CALLED"
		exit 1
		;;
esac
